trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

schedules:  # This cron expression schedules the pipeline to run every Tuesday at 9am GMT
- cron: '0 9 * * 2'
  displayName: Weekly CG run
  always: true
  branches:
    include:
    - main
    
steps:
- script: |
    export PipReportOverrideBehavior="SourceCodeScan"
    echo $PipReportOverrideBehavior
    pip install --upgrade pip 
    pip --version
    which pip
    pip install uv
    uv venv .venv --python 3.10 && source .venv/bin/activate
    uv pip compile pyproject.toml -o requirements.txt
    # too.uv.sources information is ignored by the pip compile command, manually add the individual URLs to the wheels for torch.
    # See https://github.com/astral-sh/uv/issues/8846
    sed -i 's|torch==2.2.1+cu118|torch @ https://download.pytorch.org/whl/cu118/torch-2.2.1%2Bcu118-cp310-cp310-linux_x86_64.whl#sha256=438668ad1eec3a7d1a0473ebf8b60f4557e51548d6be0497d32cc6c3a26a1945|g' requirements.txt
    sed -i 's|torchaudio==2.2.1+cu118|torchaudio @ https://download.pytorch.org/whl/cu118/torchaudio-2.2.1%2Bcu118-cp310-cp310-linux_x86_64.whl#sha256=734db8030b3c5ff6bb4135b0d0a9eec79690900c5b5edd259f230b02d6fbcb04|g' requirements.txt
    sed -i 's|torchvision==0.17.1+cu118|torchvision @ https://download.pytorch.org/whl/cu118/torchvision-0.17.1%2Bcu118-cp310-cp310-linux_x86_64.whl#sha256=dfe27be6328d85300ba9c2f3862993841c41a0daa4b4ba99c22e9fd509a21e2f|g' requirements.txt
  displayName: 'Export dependencies'

- task: ComponentGovernanceComponentDetection@0
  env:
    PipReportOverrideBehavior: SourceCodeScan
